name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ hashFiles('./package-lock.json') }}

      - name: "Install Composer Dependency"
        uses: "php-actions/composer@v6"
        with:
          php_version: "8.1"

      - name: "Install NPM Dependency"
        uses: "actions/setup-node@v3"
        with:
          node-version: "16.x"

      - name: "Install NPM Dependency"
        run: "npm install"

      - name: "Generate .env file"
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: "Test Project"
        run: "php artisan test"

  Deploy:
    needs: Testing
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ hashFiles('./package-lock.json') }}

      - name: "Install Composer Dependency"
        uses: "php-actions/composer@v6"

      - uses: action/nodejs-setup@v3
      - name: "Install NPM Dependency"
        run: |
          npm install
          npm run build

      - name: Stop Docker Containers
        run: docker-compose down -v --rmi local

      - name: Build Docker Containers
        run: docker-compose up -d
