name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ hashFiles('./package-lock.json') }}

      - name: "Install NPM Dependency"
        uses: "actions/setup-node@v3"
        with:
          node-version: "16.x"

      - name: "Install Composer Dependency"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: "Install PHP Dependency"
        run: "composer install"

      - name: "Install NPM Dependency"
        run: "npm install"

      - name: "Generate .env file"
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: "Test Project"
        run: "php artisan test"

  Deploy:
    needs: Testing
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: composer-${{ hashFiles('./composer.lock') }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-${{ hashFiles('./package-lock.json') }}

      - name: "Install NPM Dependency"
        uses: "actions/setup-node@v3"
        with:
          node-version: "16.x"

      - name: "Install NPM Dependency"
        run: npm install

      - name: "Build Project"
        run: npm run build

      - name: Stop Docker Containers
        run: docker-compose down -v --rmi local
        on-error: continue

      - name: Build Docker Containers
        run: docker-compose up -d
